import MASSTEST

DOOR_NUMBER=3#门的总数
HOST_NUMBER=1#主持人选择错误的门数
N=50000
CHANGE=MASSTEST.CHANGE_DOOR(N,DOOR_NUMBER,HOST_NUMBER)
NOT_CHANGE=MASSTEST.NOT_CHANGE_DOOR(N,DOOR_NUMBER,HOST_NUMBER)

print("进行更换的概率:",CHANGE/N)
print("不进行更换的概率:",NOT_CHANGE/N)